[package]
name = "fieldname-access"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "=1.0.35"
syn = { version = "=2.0.52", features = ["derive","full", "extra-traits"] }
proc-macro2 = "=1.0.78"
itertools = "=0.10.3"
